[application]

[web.app]

# HTML title tag content
title = "alignment_rs"

# Additional CSS style files
style = []

[bundle]
identifier = "Alignment Rs"
description = "Desktop app for visualizing the Smith-Waterman algorithm"
publisher = "Oscar Aspelin"
icon = ["assets/icon/32x32.png", "assets/icon/16x16.png"]
